# travis config, based on https://github.com/craigcitro/r-travis

language: c

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - BOOTSTRAP_LATEX=""
##    - R_BUILD_ARGS="--no-manual"
##    - R_CHECK_ARGS="--no-manual --as-cran"
##    - BOOTSTRAP_LATEX="true"

script: ./travis-tool.sh run_tests

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
##  - (cd /tmp && curl -OL http://mirrors.ctan.org/macros/latex/contrib/xcolor.zip && cd /usr/share/texmf/tex/latex && sudo unzip /tmp/xcolor.zip && cd xcolor && sudo latex xcolor.ins && sudo texhash)

install:
#  - ./travis-tool.sh github_package testthat
#  - ./travis-tool.sh github_package assertthat
#  - ./travis-tool.sh install_r_binary r.methodss3 r.oo r.utils
  - ./travis-tool.sh install_deps

branches:
  except:
   - /-expt$/

notifications:
  email:
    on_success: travis_report@aroma-project.org
    on_failure: travis_report@aroma-project.org
