#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      r_github_packages:
      - jimhester/covr
      after_success:
      - Rscript -e 'covr::codecov(quiet=FALSE)'
      env: NB='w/ covr' ## Just a label
    - os: linux
      r: devel
    - os: osx
      r: oldrel
      latex: false
      r_build_args: --no-build-vignettes
      r_check_args: --as-cran --no-vignettes
      r_github_packages:
      - HenrikBengtsson/R.cache
    - os: osx
      r: release
      latex: false
      r_build_args: --no-build-vignettes
      r_check_args: --as-cran --ignore-vignettes
      r_github_packages:
      - HenrikBengtsson/R.cache

r_packages:
    - R.rsp
   
notifications:
  email:
    on_success: change
    on_failure: change
