###########################################################################/**
# @RdocFunction buildVignette
#
# @title "Builds a vignette"
#
# \description{
#  @get "title" into a PDF or a HTML file.
# }
#
# @synopsis
#
# \arguments{
#   \item{file}{A character string specifying the vignette source file.}
#   \item{dir}{A character string specifying the working directory.}
#   \item{latex}{A logical specifying whether a TeX produced by weave
#     should be compiled by \link{texi2pdf} or not.}
#   \item{tangle}{A logical specifying whether tangle should be run or not.}
#   \item{quiet}{A logical specifying whether weave, \link{texi2pdf}, and
#     tangle should be run in quiet mode or not.}
#   \item{clean}{Remove all files generated by the build, even if there
#     were copies there before.}
#   \item{...}{Additional arguments passed to weave and tangle.}
# }
#
# \value{
#   Returns the filename to the final vignette (PDF or HTML) product.
#   If \code{latex = FALSE}, it may be a TeX file.
# }
#
# @author
#
# @keyword file
# @keyword IO
# @keyword internal
#*/########################################################################### 
buildVignette <- function(file, dir = ".", latex = TRUE, tangle = TRUE, quiet = TRUE, clean = TRUE, ...) {
    require("tools") || throw("Package not loaded: tools")
    .get_vignette_metadata <- tools:::.get_vignette_metadata
    vignette_is_tex <- tools:::vignette_is_tex
    find_vignette_product <- tools:::find_vignette_product
    vignetteEngine <- tools:::vignetteEngine
    file_path_as_absolute <- tools::file_path_as_absolute
    texi2pdf <- tools::texi2pdf
    list.files <- function(..., no..=FALSE) {
      res <- base::list.files(...);
      if (no..) res <- setdiff(res, c(".", ".."));
      res;
    }

    if (!file_test("-f", file))
        stop("No such file: ", file)

    if (!file_test("-d", dir))
        stop("Cannot set working directory. No such directory: ", dir)

    # Identify vignette engine
    lines <- readLines(file, warn=FALSE)
    engineName <- .get_vignette_metadata(lines, "Engine")
    if (length(engineName) == 0L)
        engineName <- "utils::Sweave"

    # Load vignette engine package, iff specified
    # HB: Should this be done by vignetteEngine()?
    parts <- strsplit(engineName, split="::", fixed=TRUE)[[1L]]
    if (length(parts) == 2L) {
        enginePkg <- parts[1L]
        loadNamespace(enginePkg)
    }

    # Get the vignette engine
    engine <- vignetteEngine(engineName)

    # Infer the vignette name
    names <- sapply(engine$pattern, FUN = gsub, "", file)
    name <- basename(names[(names != file)][1L])

    # Set working directory temporarily
    if (dir != ".") {
      file <- file_path_as_absolute(file)
      wd <- getwd()
      if (is.null(wd))
          stop("current working directory cannot be ascertained")
      setwd(dir)
      on.exit({
          setwd(wd)
      })
    }

    # Record existing files
    if (clean) {
        origfiles <- list.files(all.files = TRUE)
        file.create(".build.timestamp")
    }

    # Sweave
    engine$weave(file, quiet = quiet, ...)
    output <- find_vignette_product(name, by = "weave", engine = engine)

    # Compile TeX to PDF?
    if(latex && vignette_is_tex(output)) {
        texi2pdf(file = output, clean = FALSE, quiet = quiet)
        final <- find_vignette_product(name, by = "texi2pdf", engine = engine)
    } else {
        final <- output
    }
    
    # Tangle
    if (tangle) {
        engine$tangle(file, quiet = quiet, ...)
        sources <- find_vignette_product(name, by = "tangle", main = FALSE, engine = engine)
    } else
        sources <- NULL

    # Cleanup
    # NOTE: TeX file is useful for visually impared, cf. JR. Godfrey,
    #       'Statistical Software from a Blind Person's Perspective', 
    #       The R Journal, 2013 (to appear).
    keep <- c(output, sources, final)[-1L]
    if (clean) {
        f <- setdiff(list.files(all.files = TRUE, no.. = TRUE), keep)
        newer <- file_test("-nt", f, ".build.timestamp")
        ## some packages create directories
        unlink(f[newer], recursive = TRUE)
    }
    f <- setdiff(list.files(all.files = TRUE, no.. = TRUE), c(keep, origfiles))
    f <- f[file_test("-f", f)]
    file.remove(f) 

    final
} # buildVignette()


############################################################################
# HISTORY:
# 2013-03-08
# o Added buildVignette(). Code such that it could go into 'tools' with
#   only minor adjustments.
############################################################################
