###########################################################################/**
# @RdocClass RspProduct
#
# @title "The RspProduct class"
#
# \description{
#  @classhierarchy
#
#  An RspProduct object represents an RSP product generated by processing
#  an RSP document.
# }
# 
# @synopsis
#
# \arguments{
#   \item{object}{The RSP product.}
#   \item{type}{The content type of the RSP product.}
#   \item{...}{Not used.}
# }
#
# \section{Fields and Methods}{
#  @allmethods
# }
# 
# @author
#
# @keyword internal
#*/###########################################################################
setConstructorS3("RspProduct", function(object=NA, type=attr(object, "type"), ...) {
  # Argument 'type':
  if (is.null(type)) {
    type <- NA;
  }

  this <- extend(object, "RspProduct");
  attr(this, "type") <- as.character(type);
  this;
})



#########################################################################/**
# @RdocMethod print
#
# @title "Prints a summary of an RSP product"
#
# \description{
#  @get "title".
# }
#
# @synopsis
#
# \arguments{
#   \item{...}{Not used.}
# }
#
# \value{
#  Returns nothing.
# }
#
# @author
#
# \seealso{
#   @seeclass
# }
#*/######################################################################### 
setMethodS3("print", "RspProduct", function(x, ...) {
  s <- sprintf("%s:", class(x)[1L]);
  s <- c(s, sprintf("Content type: %s", getType(x)));
  s <- c(s, sprintf("Has processor: %s", hasProcessor(x)));
  s <- paste(s, collapse="\n");
  cat(s, "\n", sep="");
}, protected=TRUE)



#########################################################################/**
# @RdocMethod getType
#
# @title "Gets the type of an RSP product"
#
# \description{
#  @get "title".
# }
#
# @synopsis
#
# \arguments{
#   \item{...}{Not used.}
# }
#
# \value{
#  Returns a @character string.
# }
#
# @author
#
# \seealso{
#   @seeclass
# }
#*/######################################################################### 
setMethodS3("getType", "RspProduct", function(object, ...) {
  type <- attr(object, "type");
  if (is.null(type)) type <- NA;
  type <- tolower(type);
  type;
}, protected=TRUE)



###########################################################################/**
# @RdocMethod hasProcessor
#
# @title "Checks whether a processor exist or not for an RSP product"
#
# \description{
#  @get "title".
# }
#
# @synopsis
#
# \arguments{
#   \item{...}{Not used.}
# }
#
# \value{
#   Returns @TRUE if one exists, otherwise @FALSE.
# }
#
# @author
#
# @keyword file
# @keyword IO
#*/########################################################################### 
setMethodS3("hasProcessor", "RspProduct", function(object, ...) {
  !is.null(findProcessor(object, ...));
}, protected=TRUE)



###########################################################################/**
# @RdocMethod findProcessor
#
# @title "Tries to locate a processor for an RSP product"
#
# \description{
#  @get "title".
# }
#
# @synopsis
#
# \arguments{
#   \item{pathname}{The RSP product, e.g. a file.}
#   \item{type}{A @character string specifying the content type.}
#   \item{outPath}{The working directory.}
#   \item{...}{Not used.}
#   \item{verbose}{See @see "R.utils::Verbose".}
# }
#
# \value{
#   Returns the processed RSP product, e.g. the pathname to a PDF file.
# }
#
# @author
#
# @keyword file
# @keyword IO
#*/########################################################################### 
setMethodS3("findProcessor", "RspProduct", function(object, ..., verbose=FALSE) {
  # Load the package (super quietly), in case R.rsp::rsp() was called.
  suppressPackageStartupMessages(require("R.rsp", quietly=TRUE)) || throw("Package not loaded: R.rsp");


  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # Validate arguments
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # Argument 'verbose':
  verbose <- Arguments$getVerbose(verbose);
  if (verbose) {
    pushState(verbose);
    on.exit(popState(verbose));
  }


  verbose && enter(verbose, "Locating document-type specific processor");
  type <- getType(object);
  verbose && cat(verbose, "RSP product content type: ", type);

  # Nothing to do?
  if (is.na(type)) {
    verbose && cat(verbose, "Processor found: <none>");
    verbose && exit(verbose);
    return(NULL);
  }


  # Find another RSP compiler
  processors <- list(
    # RSP-embedded LaTeX documents:
    # *.tex => ... => *.dvi/*.pdf
    "tex" = compileLaTeX,
    "latex" = compileLaTeX,

    # RSP-embedded Sweave and Knitr Rnw documents:
    # *.Rnw => ... => *.tex => dvi/*.pdf
    "sweave" = compileSweave,

    # RSP-embedded Sweave and Knitr Rnw documents:
    # *.Rnw => ... => *.tex => dvi/*.pdf
    "knitr" = compileKnitr,

    # RSP-embedded Sweave and Knitr Rnw documents:
    # *.Rnw => ... => *.tex => dvi/*.pdf
    "rnw" = compileRnw
  );


  fcn <- NULL;
  for (key in names(processors)) {
    pattern <- key;
    if (regexpr(pattern, type) != -1) {
      fcn <- processors[[key]];
      verbose && cat(verbose, "Match: ", key);
      break;
    }
  } # for (key ...)

  if (is.null(fcn)) {
    verbose && cat(verbose, "Processor found: <none>");
  } else {
    verbose && cat(verbose, "Processor found: ", type);
  }

  verbose && exit(verbose);

  fcn;
}, protected=TRUE) # findProcessor()


###########################################################################/**
# @RdocMethod process
#
# @title "Processes an RSP product"
#
# \description{
#  @get "title".
# }
#
# @synopsis
#
# \arguments{
#   \item{...}{Not used.}
# }
#
# \value{
#   Returns the processed RSP product, which is another @see RspProduct.
# }
#
# @author
#
# @keyword file
# @keyword IO
#*/########################################################################### 
setMethodS3("process", "RspProduct", abstract=TRUE)


############################################################################
# HISTORY:
# 2013-02-13
# o Added RspProduct and RspFileProduct with corresponding 
#   process() methods.
# o Created.
############################################################################
